// --- SMART GSM - INVENTARIO CONSOLIDADO ---

const stock = [
    // --- iPHONE ---
            // --- IPHONE ---
{ m: "IPHONE", mod: "6", c: "Estándar", p: "8.000", s: "Disponible" },
{ m: "IPHONE", mod: "6s Plus", c: "Estándar", p: "16.000", s: "Disponible" },
{ m: "IPHONE", mod: "7", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "IPHONE", mod: "7 Plus", c: "Estándar", p: "13.000", s: "Disponible" },
{ m: "IPHONE", mod: "8 / SE 2020 / SE 2022", c: "ESR", p: "10.000", s: "Disponible" },
{ m: "IPHONE", mod: "8 Plus", c: "Estándar", p: "14.000", s: "Disponible" },
{ m: "IPHONE", mod: "X", c: "Oled", p: "35.000", s: "Disponible" },
{ m: "IPHONE", mod: "X", c: "Incell", p: "22.000", s: "Disponible" },
{ m: "IPHONE", mod: "XR", c: "Incell", p: "13.000", s: "Disponible" },
{ m: "IPHONE", mod: "XS", c: "Oled", p: "38.000", s: "Disponible" },
{ m: "IPHONE", mod: "XS", c: "Incell", p: "22.000", s: "Disponible" },
{ m: "IPHONE", mod: "XS Max", c: "Oled", p: "43.000", s: "Disponible" },
{ m: "IPHONE", mod: "XS Max", c: "Incell", p: "25.000", s: "Disponible" },
{ m: "IPHONE", mod: "11", c: "Incell", p: "13.000", s: "Disponible" },
{ m: "IPHONE", mod: "11 Pro", c: "Incell", p: "24.000", s: "Disponible" },
{ m: "IPHONE", mod: "11 Pro", c: "Oled", p: "36.000", s: "AGOTADA" },
{ m: "IPHONE", mod: "11 Pro Max", c: "Oled", p: "55.000", s: "Disponible" },
{ m: "IPHONE", mod: "11 Pro Max", c: "Incell", p: "26.000", s: "Disponible" },
{ m: "IPHONE", mod: "12 Mini", c: "Incell JK", p: "32.000", s: "Disponible" },
{ m: "IPHONE", mod: "12 Mini", c: "Oled", p: "76.000", s: "Disponible" },
{ m: "IPHONE", mod: "12 / 12 Pro", c: "JK Oled", p: "45.000", s: "Disponible" },
{ m: "IPHONE", mod: "12 / 12 Pro", c: "Incell JK", p: "25.000", s: "Disponible" },
{ m: "IPHONE", mod: "12 Pro Max", c: "Oled", p: "75.000", s: "Disponible" },
{ m: "IPHONE", mod: "12 Pro Max", c: "Incell JK", p: "35.000", s: "Disponible" },
{ m: "IPHONE", mod: "12 Pro Max", c: "Incell", p: "18.000", s: "Disponible" },
{ m: "IPHONE", mod: "13 Mini", c: "Oled", p: "70.000", s: "AGOTADA" },
{ m: "IPHONE", mod: "13 Mini", c: "Incell", p: "33.000", s: "Disponible" },
{ m: "IPHONE", mod: "13", c: "Soft Oled JK", p: "42.000", s: "Disponible" },
{ m: "IPHONE", mod: "13", c: "Incell AAA", p: "27.000", s: "Disponible" },
{ m: "IPHONE", mod: "13 Pro", c: "Incell JK", p: "27.000", s: "Disponible" },
{ m: "IPHONE", mod: "13 Pro", c: "Incell", p: "23.000", s: "Disponible" },
{ m: "IPHONE", mod: "13 Pro", c: "GX Oled", p: "65.000", s: "Disponible" },
{ m: "IPHONE", mod: "13 Pro Max", c: "GX Oled", p: "65.000", s: "Disponible" },
{ m: "IPHONE", mod: "13 Pro Max", c: "Incell JK", p: "34.000", s: "Disponible" },
{ m: "IPHONE", mod: "13 Pro Max", c: "Incell", p: "24.000", s: "Disponible" },
{ m: "IPHONE", mod: "14", c: "JK Oled", p: "50.000", s: "Disponible" },
{ m: "IPHONE", mod: "14 Pro", c: "GX Oled", p: "95.000", s: "Disponible" },
{ m: "IPHONE", mod: "14 Pro", c: "GY YK Incell", p: "20.000", s: "Disponible" },
{ m: "IPHONE", mod: "14 Pro Max", c: "Incell JK", p: "38.000", s: "AGOTADA" },
{ m: "IPHONE", mod: "14 Pro Max", c: "Incell", p: "26.000", s: "Disponible" },
{ m: "IPHONE", mod: "14 Pro Max", c: "GX Oled", p: "122.000", s: "Disponible" },
{ m: "IPHONE", mod: "15", c: "Incell GY", p: "19.000", s: "Disponible" },
{ m: "IPHONE", mod: "15", c: "Oled RJ", p: "61.000", s: "Disponible" },
{ m: "IPHONE", mod: "15 Pro", c: "Incell GY", p: "20.000", s: "Disponible" },
{ m: "IPHONE", mod: "15 Pro Max", c: "Incell JK", p: "38.000", s: "Disponible" },
{ m: "IPHONE", mod: "15 Pro Max", c: "Oled RJ Soft", p: "62.000", s: "Disponible" },
{ m: "IPHONE", mod: "16", c: "RJ Soft", p: "62.000", s: "Disponible" },
{ m: "IPHONE", mod: "16", c: "JK Incell", p: "36.000", s: "Disponible" },
{ m: "IPHONE", mod: "16 Pro", c: "Oled RJ", p: "98.000", s: "Disponible" },
{ m: "IPHONE", mod: "16 Pro Max", c: "Oled RJ Soft", p: "73.000", s: "Disponible" },


// --- SAMSUNG ---
{ m: "SAMSUNG", mod: "A01M", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A03/A02s/A03s", c: "Estándar", p: "10.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "A03 Core", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A04", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A04E", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A04S", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A05", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A05S", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A06 4G", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A06 5G", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A7 2018", c: "Oled", p: "39.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A7 2018", c: "Incell", p: "12.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "A10", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A10s", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A11", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A12/A02", c: "Estándar", p: "9.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "A13 4G", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A13 5G", c: "Estándar", p: "15.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A14 5G", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A15", c: "Oled c/m", p: "37.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A15", c: "Incell c/m", p: "13.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A16 4G", c: "Incell c/m", p: "18.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "A16 4G", c: "Orig S/M", p: "70.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A16 5G", c: "Incell c/m", p: "14.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A16 5G", c: "Orig S/M", p: "70.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A20", c: "Oled", p: "28.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A20", c: "Incell c/m", p: "12.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A20s", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A21S", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A22 4G", c: "Incell c/m", p: "13.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A22 5G", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A23 4G", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A23 5G", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A24", c: "Incell c/m", p: "13.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A24 5G", c: "Original", p: "85.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A25", c: "Original", p: "76.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "A25", c: "Oled", p: "49.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "A25", c: "Incell c/m", p: "13.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A30", c: "Incell c/m", p: "12.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A30/A50", c: "Oled", p: "24.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A30s", c: "Oled", p: "28.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A30S", c: "Incell c/m", p: "11.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A31", c: "Oled c/m", p: "26.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A31", c: "Incell c/m", p: "13.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A32 4G", c: "Oled c/m", p: "27.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A32 4G", c: "Incell c/m", p: "13.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A32 5G", c: "Estándar", p: "15.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A33", c: "Oled c/m", p: "33.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "A33", c: "Incell c/m", p: "17.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A34", c: "Oled c/m", p: "40.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "A34", c: "Incell c/m", p: "14.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A35", c: "Original", p: "87.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "A35", c: "Incell c/m", p: "21.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "A36 5G", c: "Incell c/m", p: "25.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A50", c: "Incell c/m", p: "14.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A51", c: "Oled c/m", p: "28.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A51", c: "Incell c/m", p: "12.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A52", c: "Oled c/m", p: "35.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A52S", c: "Oled c/m", p: "35.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A52S", c: "Incell c/m", p: "15.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A53", c: "Incell c/m", p: "15.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A53", c: "Oled c/m", p: "36.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "A54", c: "Oled c/m", p: "36.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "A54", c: "Incell c/m", p: "16.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A55", c: "Oled c/m", p: "40.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A55", c: "Incell c/m", p: "22.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A56", c: "Incell c/m", p: "21.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A70", c: "Incell c/m", p: "15.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "A70", c: "Oled Full C/M", p: "46.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "A71", c: "Incell c/m", p: "16.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A71", c: "Oled c/m", p: "35.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A72", c: "Incell c/m", p: "16.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A72", c: "Oled c/m", p: "39.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "A73", c: "Incell c/m", p: "21.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "A73", c: "Original", p: "83.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "A80", c: "Estándar", p: "45.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "J4", c: "Incell", p: "13.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "J4", c: "Oled", p: "28.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "J4+/J6+/J4 core", c: "Estándar", p: "13.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "J6", c: "Incell", p: "14.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "J7 Prime", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "J7 Pro", c: "Estándar", p: "27.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "J8", c: "Oled", p: "37.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "M22", c: "Oled c/m", p: "55.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "M32", c: "Oled c/m", p: "55.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "Note 10 Lite", c: "Oled", p: "55.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "S20 FE", c: "Incell", p: "13.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "S20 FE", c: "Original", p: "79.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "S20 FE", c: "Oled c/m", p: "37.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "S21 FE", c: "Estándar", p: "137.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "S21 FE", c: "Oled", p: "34.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "S21 5G", c: "Oled", p: "73.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "S21 Ultra", c: "Oled c/m", p: "104.000", s: "AGOTADA" },
{ m: "SAMSUNG", mod: "S23", c: "Original", p: "151.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "S23 FE", c: "Original", p: "82.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "S23 Plus", c: "Original", p: "125.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "S24", c: "Original", p: "155.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "S24 Plus", c: "Estándar", p: "159.000", s: "Disponible" },
{ m: "SAMSUNG", mod: "S24 FE", c: "Original", p: "85.000", s: "Disponible" },
    

    // --- XIAOMI / POCO ---
{ m: "XIAOMI", mod: "Redmi A1", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi A3", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi A5", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi 8 / 8A", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi Note 8", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi Note 8 Pro", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi 9", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi 9T / Poco M3", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi 9A / 9C / 10A", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi Note 9", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi Note 9 Pro / 9S", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi 10 4G", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi 10C / Poco C40", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi 10 5G / Note 11E / Poco M5", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Mi 9T", c: "Oled", p: "43.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Mi 10T / Mi 10T Pro", c: "Original", p: "20.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi Note 10 5G / Poco M3 Pro", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi Note 10S / 10 4G", c: "Oled", p: "28.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi Note 10S / 10 4G", c: "Incell", p: "11.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Mi Note 10 / 10 Lite / 10 Pro", c: "Oled", p: "39.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi Note 10 Pro / Note 11 Pro / Poco X4 Pro", c: "Oled", p: "34.000", s: "AGOTADA" },
{ m: "XIAOMI", mod: "Redmi Note 10 Pro", c: "Incell c/m", p: "16.000", s: "AGOTADA" },
{ m: "XIAOMI", mod: "Redmi Note 11 Pro", c: "Incell c/m", p: "17.000", s: "AGOTADA" },
{ m: "XIAOMI", mod: "Mi 11 Lite 5G NE", c: "Oled", p: "46.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Mi 11 Lite 4G", c: "Oled", p: "42.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Mi 11 Lite", c: "Incell c/m", p: "20.000", s: "AGOTADA" },
{ m: "XIAOMI", mod: "Mi 11T / 11T Pro", c: "Oled", p: "39.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Mi 11T / 11T Pro", c: "Incell", p: "13.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi Note 11S / 12S 4G", c: "Oled", p: "31.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi Note 11 / 11S / 12S", c: "Incell S/M", p: "11.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi 12 5G", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi 12C", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi Note 12 4G / 5G", c: "Oled", p: "40.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi Note 12 4G / 5G", c: "Incell c/m", p: "14.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi Note 12 4G / 5G", c: "Incell", p: "12.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi Note 12 Pro 5G / Poco X5 Pro", c: "Original", p: "33.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Mi 12 Lite", c: "Original", p: "49.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Mi 12", c: "Original", p: "82.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Mi 12 Pro", c: "Original", p: "155.000", s: "AGOTADA" },
{ m: "XIAOMI", mod: "Mi 12T / 12T Pro", c: "Original", p: "42.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Mi 13T", c: "Original", p: "37.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Xiaomi 14", c: "Original", p: "52.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Xiaomi 14 Pro", c: "Original", p: "70.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Xiaomi 14T / 14T Pro", c: "Original", p: "30.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Xiaomi 15", c: "Original", p: "70.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi Note 13 4G", c: "Original", p: "62.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi Note 13 5G", c: "Original", p: "23.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi Note 13 Pro 5G / Poco X6", c: "Original", p: "31.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi Note 13 Pro Plus / Redmi Note 14 Pro Plus 5G", c: "Original", p: "37.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi 13C / Poco C65", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi 14C", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi 15C", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Redmi Note 14 4G / 5G / Poco M7 Pro", c: "Original", p: "67.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Poco F3", c: "Oled", p: "43.000", s: "AGOTADA" },
{ m: "XIAOMI", mod: "Poco F3", c: "Incell c/m", p: "21.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Poco M4 Pro 5G / Note 11S 5G", c: "Original", p: "20.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Poco M5", c: "Original", p: "18.000", s: "AGOTADA" },
{ m: "XIAOMI", mod: "Poco X3 / Mi 10T Lite", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Poco X3 GT / Redmi Note 10 Pro 5G", c: "Original", p: "19.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Poco X4 GT", c: "Original", p: "22.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Poco X5", c: "Oled", p: "63.000", s: "AGOTADA" },
{ m: "XIAOMI", mod: "Poco X6 Pro 5G", c: "Original", p: "34.000", s: "Disponible" },
{ m: "XIAOMI", mod: "Poco X7", c: "Original", p: "37.000", s: "Disponible" },

    // --- MOTOROLA ---
{ m: "MOTOROLA", mod: "E6+", c: "Estándar", p: "13.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "E6s / E6i", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "E7 / E7i Power", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "E13", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "E15 / G05", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "E20", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "E22 / E22i", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "E30 / E40", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G04 / G04s / G24 / G24 Power / E14", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G06 / G06 Power", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G7 / G7 Plus", c: "Estándar", p: "20.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G7 Power", c: "Estándar", p: "16.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G8 Play", c: "Estándar", p: "15.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G8 Plus", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G8 Power", c: "Estándar", p: "13.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G8 Power Lite", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G9 Play / E7 Plus", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G9 Plus", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G9 Power", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G13 / G23 / G34 5G / G53 5G", c: "Estándar", p: "9.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G14 / G54 / G55 5G", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G15 / G15 Power", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G20 / G30", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G22 / E32", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G31 / G41 / G71", c: "Oled", p: "30.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G35 5G", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G42", c: "Oled", p: "34.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G50 4G", c: "Estándar", p: "20.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G50 5G", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G56", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G51 / G60 / G60S", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G82", c: "Original", p: "47.000", s: "AGOTADA" },
{ m: "MOTOROLA", mod: "G84", c: "Incell", p: "13.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G84", c: "Oled", p: "47.000", s: "AGOTADA" },
{ m: "MOTOROLA", mod: "G84", c: "Original", p: "56.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "G100", c: "Original", p: "24.000", s: "AGOTADA" },
{ m: "MOTOROLA", mod: "G200", c: "Original", p: "25.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "One Fusion", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "One Action", c: "Original", p: "45.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "One Hyper", c: "Original", p: "18.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "Edge 20 Lite", c: "Oled", p: "44.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "Edge 20 Lite", c: "Incell c/m", p: "21.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "Edge 40 / Edge 40 Neo", c: "Oled", p: "36.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "Edge 30 Fusion", c: "Oled", p: "52.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "Edge 30 Neo", c: "Original", p: "64.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "Edge 50 Fusion", c: "Original", p: "32.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "Edge 50 Pro 5G", c: "Original", p: "42.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "Edge 50 Ultra", c: "Original", p: "71.000", s: "Disponible" },
{ m: "MOTOROLA", mod: "Edge 60 / Edge 60S / Edge 60 Fusion", c: "Original", p: "40.000", s: "Disponible" },

    // --- HONOR ---
{ m: "HONOR", mod: "X5B / X6A / X6A Plus / X5 Plus", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "HONOR", mod: "X5B / X5B Plus", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "HONOR", mod: "X8A 5G", c: "Estándar", p: "13.000", s: "Disponible" },
{ m: "HONOR", mod: "X8C", c: "Original", p: "31.000", s: "Disponible" },
{ m: "HONOR", mod: "X6 / X6s / X8A 5G", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "HONOR", mod: "X6B", c: "Estándar", p: "12.000", s: "AGOTADA" },
{ m: "HONOR", mod: "X7C / X6B 5G", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "HONOR", mod: "X7", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "HONOR", mod: "X7A", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "HONOR", mod: "X7B / 90 Smart", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "HONOR", mod: "X8 4G (TFY)", c: "Original", p: "15.000", s: "Disponible" },
{ m: "HONOR", mod: "X8B / 200 Lite", c: "Original", p: "38.000", s: "Disponible" },
{ m: "HONOR", mod: "X8A 4G (CRT) / 90 Lite", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "HONOR", mod: "X9 4G / X9 5G", c: "Estándar", p: "13.000", s: "Disponible" },
{ m: "HONOR", mod: "X9C / X9C Smart 5G", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "HONOR", mod: "Honor 90", c: "Original", p: "46.000", s: "Disponible" },
{ m: "HONOR", mod: "Magic 5 Lite", c: "Original", p: "33.000", s: "Disponible" },
{ m: "HONOR", mod: "Magic 6 Lite", c: "Original", p: "43.000", s: "Disponible" },
{ m: "HONOR", mod: "Magic 7 Lite", c: "Original", p: "34.000", s: "Disponible" },
{ m: "HONOR", mod: "Honor 400 Lite", c: "Original", p: "28.000", s: "Disponible" },
{ m: "HONOR", mod: "Honor 400 Smart", c: "Estándar", p: "12.000", s: "Disponible" },

    // --- HUAWEI ---
{ m: "HUAWEI", mod: "Nova 5T", c: "Estándar", p: "14.000", s: "Disponible" },
{ m: "HUAWEI", mod: "Nova 8i", c: "Estándar", p: "14.000", s: "AGOTADA" },
{ m: "HUAWEI", mod: "Nova 9 SE", c: "Estándar", p: "14.000", s: "Disponible" },
{ m: "HUAWEI", mod: "Nova Y60", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "HUAWEI", mod: "Nova Y70", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "HUAWEI", mod: "Nova Y90", c: "Estándar", p: "16.000", s: "Disponible" },
{ m: "HUAWEI", mod: "P20 Lite", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "HUAWEI", mod: "P30 Lite", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "HUAWEI", mod: "P30", c: "Oled", p: "35.000", s: "AGOTADA" },
{ m: "HUAWEI", mod: "P30 Pro", c: "Oled", p: "67.000", s: "AGOTADA" },
{ m: "HUAWEI", mod: "P40 Lite", c: "Estándar", p: "14.000", s: "Disponible" },
{ m: "HUAWEI", mod: "P40 Lite 5G / Nova 7 SE", c: "Estándar", p: "18.000", s: "Disponible" },
{ m: "HUAWEI", mod: "Mate 10 Lite", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "HUAWEI", mod: "Mate 20 Lite", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "HUAWEI", mod: "P Smart 2019", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "HUAWEI", mod: "Y6 2019", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "HUAWEI", mod: "Y6P", c: "Estándar", p: "12.000", s: "AGOTADA" },
{ m: "HUAWEI", mod: "Y7A", c: "Estándar", p: "13.000", s: "Disponible" },
{ m: "HUAWEI", mod: "Y7P", c: "Estándar", p: "14.000", s: "Disponible" },
{ m: "HUAWEI", mod: "Y7 2019", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "HUAWEI", mod: "Y8P", c: "Incell", p: "16.000", s: "AGOTADA" },
{ m: "HUAWEI", mod: "Y8P", c: "Oled", p: "35.000", s: "AGOTADA" },
{ m: "HUAWEI", mod: "Y9 2019 / Y8S", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "HUAWEI", mod: "Y9A", c: "AAA", p: "16.000", s: "Disponible" },
{ m: "HUAWEI", mod: "Y9A", c: "Original", p: "19.000", s: "Disponible" },
{ m: "HUAWEI", mod: "Y9 Prime 2019", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "HUAWEI", mod: "Y9s", c: "AAA", p: "10.000", s: "Disponible" },
{ m: "HUAWEI", mod: "Y9s", c: "Original", p: "18.000", s: "Disponible" },

    // --- VIVO ---
{ m: "VIVO", mod: "Y01 / Y11S / Y15S / Y20 / Y20i", c: "Estándar", p: "9.000", s: "Disponible" },
{ m: "VIVO", mod: "Y03 / Y18 / Y28S", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "VIVO", mod: "Y02S / Y16 / Y21S", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "VIVO", mod: "Y15 / Y17", c: "Estándar", p: "15.000", s: "Disponible" },
{ m: "VIVO", mod: "Y38 5G / Y19S / Y29 5G / Y39 5G", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "VIVO", mod: "Y17S / Y22 / Y22S", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "VIVO", mod: "Y27 5G", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "VIVO", mod: "Y35", c: "Estándar", p: "17.000", s: "Disponible" },
{ m: "VIVO", mod: "Y36 5G", c: "Estándar", p: "17.000", s: "Disponible" },
{ m: "VIVO", mod: "Y51 / Y52S / Y53S", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "VIVO", mod: "Y55 5G", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "VIVO", mod: "V21 5G", c: "Oled", p: "28.000", s: "Disponible" },
{ m: "VIVO", mod: "V21 5G", c: "Incell", p: "13.000", s: "Disponible" },
{ m: "VIVO", mod: "V25 5G", c: "Oled", p: "31.000", s: "Disponible" },
{ m: "VIVO", mod: "V25 Pro 5G", c: "Original", p: "45.000", s: "Disponible" },
{ m: "VIVO", mod: "V29 5G", c: "Original", p: "51.000", s: "Disponible" },
{ m: "VIVO", mod: "V30 Lite", c: "Oled", p: "38.000", s: "Disponible" },
{ m: "VIVO", mod: "V30", c: "Original", p: "39.000", s: "Disponible" },
{ m: "VIVO", mod: "V40 SE", c: "Original", p: "45.000", s: "Disponible" },

    // --- OPPO ---
{ m: "OPPO", mod: "A15", c: "Estándar", p: "14.000", s: "Disponible" },
{ m: "OPPO", mod: "A16", c: "Estándar", p: "13.000", s: "Disponible" },
{ m: "OPPO", mod: "A17 / A38 / A57", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "OPPO", mod: "A40 / A80", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "OPPO", mod: "A52 / A72 / A92", c: "Estándar", p: "14.000", s: "Disponible" },
{ m: "OPPO", mod: "A54", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "OPPO", mod: "A58", c: "Estándar", p: "13.000", s: "AGOTADA" },
{ m: "OPPO", mod: "A78 5G", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "OPPO", mod: "Reno 5 Lite / Reno 6 Lite", c: "Incell", p: "11.000", s: "Disponible" },
{ m: "OPPO", mod: "Reno 6 5G", c: "Oled", p: "49.000", s: "AGOTADA" },
{ m: "OPPO", mod: "Reno 6 5G", c: "Incell", p: "13.000", s: "Disponible" },
{ m: "OPPO", mod: "Reno 6 Lite", c: "Oled", p: "45.000", s: "AGOTADA" },
{ m: "OPPO", mod: "Reno 7 4G", c: "Incell", p: "12.000", s: "Disponible" },
{ m: "OPPO", mod: "Reno 10 5G", c: "Original", p: "45.000", s: "Disponible" },

    // --- LG ---
{ m: "LG", mod: "G Stylo H630", c: "Estándar", p: "6.000", s: "Disponible" },
{ m: "LG", mod: "G4", c: "Estándar", p: "8.000", s: "Disponible" },
{ m: "LG", mod: "K4 M160", c: "Estándar", p: "5.000", s: "Disponible" },
{ m: "LG", mod: "K8 M210", c: "Estándar", p: "8.000", s: "Disponible" },
{ m: "LG", mod: "K8 K350", c: "Estándar", p: "8.000", s: "Disponible" },
{ m: "LG", mod: "K10 K420 / K430", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "LG", mod: "K10 M320", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "LG", mod: "K22", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "LG", mod: "K40S", c: "Estándar", p: "15.000", s: "Disponible" },
{ m: "LG", mod: "K41S", c: "Estándar", p: "14.000", s: "Disponible" },
{ m: "LG", mod: "K42 / K52", c: "Estándar", p: "14.000", s: "Disponible" },
{ m: "LG", mod: "K50S", c: "Estándar", p: "15.000", s: "Disponible" },
{ m: "LG", mod: "K50 / Q60", c: "Estándar", p: "14.000", s: "Disponible" },
{ m: "LG", mod: "K51S", c: "Estándar", p: "12.000", s: "AGOTADA" },
{ m: "LG", mod: "K61", c: "Estándar", p: "18.000", s: "Disponible" },
{ m: "LG", mod: "X Cam K580", c: "Estándar", p: "18.000", s: "Disponible" },
{ m: "LG", mod: "X Power K220", c: "Estándar", p: "15.000", s: "Disponible" },
{ m: "LG", mod: "Nexus 5X", c: "Estándar", p: "15.000", s: "Disponible" },

    // --- TCL ---
{ m: "TCL", mod: "20E", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "TCL", mod: "20L / 20S", c: "Estándar", p: "21.000", s: "Disponible" },
{ m: "TCL", mod: "20SE", c: "Estándar", p: "13.000", s: "Disponible" },
{ m: "TCL", mod: "30SE / 30E / 305", c: "Estándar", p: "15.000", s: "Disponible" },
{ m: "TCL", mod: "40SE", c: "Estándar", p: "16.000", s: "Disponible" },

    // --- INFINIX ---
{ m: "INFINIX", mod: "Hot 30 4G / 5G", c: "Estándar", p: "16.000", s: "Disponible" },
{ m: "INFINIX", mod: "Hot 40i", c: "Estándar", p: "10.000", s: "Disponible" },
{ m: "INFINIX", mod: "Hot 40 Pro", c: "Estándar", p: "20.000", s: "AGOTADA" },
{ m: "INFINIX", mod: "Hot 50i", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "INFINIX", mod: "Note 30 5G", c: "Estándar", p: "18.000", s: "Disponible" },
{ m: "INFINIX", mod: "Smart 10", c: "Estándar", p: "10.000", s: "Disponible" },

    // --- ZTE ---
{ m: "ZTE", mod: "A35 / A55 4G", c: "Estándar", p: "12.000", s: "Disponible" },
{ m: "ZTE", mod: "A34 / A54 4G", c: "Estándar", p: "11.000", s: "Disponible" },
{ m: "ZTE", mod: "A73 5G", c: "Estándar", p: "14.000", s: "Disponible" },
{ m: "ZTE", mod: "A75 5G", c: "Estándar", p: "13.000", s: "Disponible" },
{ m: "ZTE", mod: "Nubia Neo 2 5G", c: "Estándar", p: "18.000", s: "Disponible" },
{ m: "ZTE", mod: "Nubia Focus 5G", c: "Estándar", p: "13.000", s: "Disponible" },

    // --- NOKIA ---
{ m: "NOKIA", mod: "5.3", c: "Estándar", p: "27.000", s: "AGOTADA" },
{ m: "NOKIA", mod: "G10 / G20", c: "Estándar", p: "15.000", s: "Disponible" },
{ m: "NOKIA", mod: "G21", c: "Estándar", p: "19.000", s: "Disponible" },
{ m: "NOKIA", mod: "N535", c: "Estándar", p: "5.000", s: "Disponible" },
{ m: "NOKIA", mod: "N630", c: "Estándar", p: "5.000", s: "Disponible" },
{ m: "NOKIA", mod: "N820", c: "Estándar", p: "5.000", s: "Disponible" },
{ m: "NOKIA", mod: "N920", c: "Estándar", p: "6.000", s: "Disponible" },
{ m: "NOKIA", mod: "N930", c: "Estándar", p: "6.000", s: "Disponible" },

    // --- TABLET ---
    { m: "TABLET", mod: "Lenovo Tab M10 HD 2nd Gen", c: "Completa", p: "28.000", s: "Disponible" }
];

// Exportar datos para la aplicación

window.inventarioSmartGSM = stock;

